enum TipoAccionEnum {

    BUSCAR_TODOS = "BUSCAR_TODOS",
    BUSCAR = "BUSCAR",
    SELECCIONAR ="SELECCIONAR",

    NUEVO_PREPARAR = 'NUEVO_PREPARAR',
    NUEVO = "NUEVO",
    ACTUALIZAR = "ACTUALIZAR",
    ELIMINAR = "ELIMINAR",
    CANCELAR = "CANCELAR",
    GUARDAR_CAMBIOS = "GUARDAR_CAMBIOS"
}

export {TipoAccionEnum};